---

- name: Check if the repository exists
  uri:
    url: "http://{{ elastic_host }}:{{ elastic_port }}/_snapshot"
    method: GET
  register: snapshot_results

- name: Create snapshot repository if it doesn't exits already
  uri:
    url: "http://{{ elastic_host }}:{{ elastic_port }}/_snapshot/{{ snapshot_repository }}"
    method: PUT
    body:
      type: s3
      settings:
        bucket: "{{ snapshot_bucket }}"
    body_format: json
  when: snapshot_results.json.snapshot_repository is not defined

- name: Create snapshot
  uri:
    url: "http://{{ elastic_host }}:{{ elastic_port }}/_snapshot/{{ snapshot_repository }}/{{ snapshot_name }}?wait_for_completion={{ wait_for_completion }}"
    method: PUT
